iterations: 12
threads: null
scheduler: GEDF_NP
savina_path: "${oc.env:SAVINA_PATH}"
lf_path: "${oc.env:LF_PATH}"
continue_on_error: False
test_mode: False
defaults:
  - benchmark: ???
  - target: ???
  - _self_
