# Build lingua-franca on the Travis Continuous Integration system
#
# Based on http://muelder.blogspot.com/2015/08/building-eclipse-plugins-with-maven.html
#
os:
  - linux
  - osx

dist: bionic
sudo: false  
language: java    
jdk:
 - oraclejdk12
cache:  
 directories:  
  - $HOME/.m2
  - $HOME/.gradle
# The node_js property doesn't work if the language is java
before_install:
  - nvm install 10.4.0
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-googleapi
      - libprotobuf-dev
      - libprotobuf-c-dev
      - protobuf-compiler
      - protobuf-c-compiler
env:
  - TEST=Unit
  - TEST=C
  - TEST=Cpp
  - TEST=Python
  - TEST=TS
# global:  
#  - DISPLAY=:99.0  
#before_install:
# - sh -e /etc/init.d/xvfb start - sleep 10  
script:
 - 'if [ ${TEST} = "Unit" ]; then
        pushd xtext;
        ./gradlew test || travis_terminate 1;
        popd;
    else
        bin/run-lf-tests $TEST || travis_terminate 1;
    fi'
