# Build lingua-franca on the Travis Continuous Integration system
#
# Based on http://muelder.blogspot.com/2015/08/building-eclipse-plugins-with-maven.html
#

sudo: false  
language: java    
jdk:
 - oraclejdk11
cache:  
 directories:  
  - $HOME/.m2  
#env:  
# global:  
#  - DISPLAY=:99.0  
#before_install:  
# - sh -e /etc/init.d/xvfb start - sleep 10  
script:    
# - jdk_switcher use oraclejdk8
# - jdk_switcher use oraclejdk11
 - bin/run-lf-tests C
 - bin/run-lf-tests Cpp
