# @package _group_
name: akka
gen: null
compile: null
run: ["java", "-classpath", "${benchmark.targets.akka.jar}",
      "${benchmark.targets.akka.class}",
      "${args:benchmark.targets.akka.run_args}"]
parser:
  _target_: "parser.parse_akka_output"
